directory mode and search for objects
arvancloud/arvans3 pull request #8
Opened 2022-12-08 13:05 UTC by nosaraei

2022-12-08 14:25 UTC, RaminNietzsche requested changes
سلام
لطفا این موارد رو با هم بررسی کنیم بیشتر در مورد استایل هست اینجوری استایل پروژه یکم یکدست میشه و توسعه‌های بعدی میتونه راحت تر باشه

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/channel/ObjectsChannel.js
> +            if(object.Prefix){
بنظر میاد مطابق کد مقدار  ‍ `object.Id` همیشه با `object.Key` یکسان هست نیاز هست به هر دو تا؟ و اگر نیاز هست میشه یکی رو تخصیص داد و بعد از شرط این دومقدار رو یکسان کرد

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/channel/ObjectsChannel.js
>              //console.log("load object from s3")
به این خط نیازی نیست

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/helper/S3Helper.js
> +    //console.log(data);
به این دو خط نیازی نیست

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/helper/S3Helper.js
> +    console.log(data);
اگر چیزی توی کنسول میاد بهتره یک حالت دیباگ داشته باشیم که فعال و غیر فعال بشه و خروجی دیباگ همیشه توی کنسول نیاد

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/helper/S3Helper.js
> +    while (nextMarker){
امکانش نیست به این شکل نوشته بشه؟ اینجوری دو خط کم میشه و خوانایی کد هم بیشتر میشه یک متغیر هم حذف میشه. :)

```suggestion
    while (data.NextMarker){
```

2022-12-08 14:25 UTC, RaminNietzsche commented on src/sections/ObjectsList/ObjectsList.js
> +        console.log(queryOptions);
اینم مثل اون کنسول قبلی، اگر فقط برای دیباگ توسعه دهنده هست حذف بشه ولی اگر برای کاربر یک قابلیت محسوب میشه به شکلی بشه کنسول رو فعال و غیرفعال کرد

2022-12-08 14:25 UTC, RaminNietzsche commented on src/sections/ObjectsList/ObjectsList.js
> +            console.log("change prefix");
این هم شامل قانون کنسول میشه :)

2022-12-08 14:25 UTC, RaminNietzsche commented on src/sections/ObjectsList/ObjectsList.js
کلا به خط اضافه بین قسمت های یک بلوک از کد نیازی نیست، حجم کد رو زیاد میکنه و خوانایی رو کم میکنه، بهتره بین بلوک‌هایی که از نظر عملکردی یا منطقی متفاوت هستن یک خط فاصله باشه و بقیه جاها نیازی به یک خط خالی نیست

2022-12-08 14:25 UTC, RaminNietzsche commented on src/sections/ObjectsList/ObjectsList.js
> +        if(objects !== null){
بقیه‌ی جاها استایل کد نویسی اینجوری هست، دلیلی داره که اینجا متفاوت نوشته شده؟
```suggestion
        if(objects){
```

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/helper/S3Helper.js
> +        Bucket: bucketName,
توی بعضی از موارد بعد از آخرین آرگومان یک کاما (`,`) درج شده ولی برای بعضی دیگه آخرین آرگومان بدون کاما نوشته شده اگر دلیلی برای این تفاوت نیست بهتره که همه یک دست باشن

2022-12-08 14:25 UTC, RaminNietzsche commented on backend/helper/S3Helper.js
> +            Marker: nextMarker
به عنوان مثال در مورد کاما (`,`) اینجا آخرین آرگومان بدون کاما نوشته شده

2022-12-15 18:45 UTC, nosaraei commented on backend/channel/ObjectsChannel.js
> +            if(object.Prefix){
سلام. وقت بخیر. آره مقادیرشون یکسان هست. ولی به هر دو نیاز هست. برای اینکه در ادامه مپ اضافه تری نداشته باشیم. همینجا مقادیرش رو ست کردم.

2022-12-15 18:47 UTC, nosaraei commented on backend/helper/S3Helper.js
> +    console.log(data);
نه لاگ ها بهتره برداشته بشن. فقط جهت تست گذاشته شده بود.

2022-12-15 18:55 UTC, nosaraei commented on backend/helper/S3Helper.js
> +    while (nextMarker){
آره بهتره.

2022-12-15 19:00 UTC, nosaraei commented on src/sections/ObjectsList/ObjectsList.js
این شیوه توی کل پروژه استفاده شده. البته فایل های سمت کلاینت همه فشرده میشن موقع اجرا.

2022-12-15 19:17 UTC, nosaraei commented on src/sections/ObjectsList/ObjectsList.js
> +        if(objects !== null){
خوانایی کد بالا میره. می خواستم اطمینان حاصل بشه که مخالف نال هست.

2022-12-15 19:20 UTC, nosaraei commented on backend/helper/S3Helper.js
> +        Bucket: bucketName,
بر می دارم. نباشه قشنگ تره.

2022-12-24 10:43 UTC, closed without merging